### ISSUE TITLE
Conversion from Arduino to Platform IO Failed.

### ISSUE THREAD

**Issue by sbfreddie** [mrWheel/arduinoIDE2platformIO-convertor#1]
I am trying to convert this codebase from Arduino to Platform IO:
https://github.com/Greg-R/T41EEE

It really is a mess, probably the best example of spaghetti code I have see in a long time.

The conversion fails, here is the output from the Terminal on my Mac:

Last login: Sun Aug 11 20:14:51 on console
freddie@Eds-MacBook-Pro ~ % cd /Users/freddie/Desktop/T41EEE-main 
freddie@Eds-MacBook-Pro T41EEE-main % python arduinoIDE2platformIO.py 
   INFO - :2311 - 
   INFO - :2312 - =======================================================================================================
   INFO - :2313 - [Step 1] Setup the folder structure for a PlatformIO project
   INFO - :2314 - =======================================================================================================
   INFO - : 113 - 
   INFO - : 114 - Processing: set_glob_project_info(T41EEE-main)
   INFO - :2317 -            Project folder: /Users/freddie/Desktop/T41EEE-main
   INFO - :2320 - 	        PlatformIO folder: ../T41EEE-main/PlatformIO
   INFO - :2321 - 	    PlatformIO src folder: ../T41EEE-main/PlatformIO/T41EEE-main/src
   INFO - :2322 - 	PlatformIO include folder: ../T41EEE-main/PlatformIO/T41EEE-main/include
   INFO - : 465 - 
   INFO - : 466 - remove_pio_tree(): ../T41EEE-main/PlatformIO, project:[T41EEE-main], preserve:[platformio.ini]
  ERROR - : 472 - 	Error: The base path '../T41EEE-main/PlatformIO' does not exist.
   INFO - : 539 - 
   INFO - : 540 - Processing: recreat_pio_folders()
   INFO - : 565 - 	PlatformIO folder structure recreated
   INFO - :2332 - 
   INFO - :2333 - =======================================================================================================
   INFO - :2334 - [Step 2] Copy all .ino, .cpp, .c and .h files from the Arduino project
   INFO - :2335 -          Copy the data folder (if it excists) from the Arduino project
   INFO - :2336 -          Create the platformio.ini file
   INFO - :2337 -          Extract all #define statements from all .ino and .h files
   INFO - :2338 - =======================================================================================================
   INFO - :1152 - 
   INFO - :1153 - Processing: copy_project_files() ..
   INFO - :1162 - 	'arduinoGlue.h' does not (yet) exist.
   INFO - : 688 - 
   INFO - : 689 - Processing: copy_data_folder()
   INFO - : 725 - 	No data folder found in the project folder
   INFO - : 730 - 
   INFO - : 731 - Processing: create _platformio_ini() if it doesn't exist in [../T41EEE-main/PlatformIO/T41EEE-main]
   INFO - : 804 - 	Created platformio.ini file at ../T41EEE-main/PlatformIO/T41EEE-main/platformio.ini
   INFO - : 816 - 
   INFO - : 820 - Searching for #define statements in ../T41EEE-main/PlatformIO
   INFO - : 891 - 	Creating arduinoGlue.h with 0 macros
   INFO - : 899 - 	Successfully created ../T41EEE-main/PlatformIO/T41EEE-main/include/arduinoGlue.h
   INFO - : 909 - 	Extracted 0 #define statements
   INFO - : 421 -  
   INFO - : 422 - Files in the directory '../T41EEE-main/PlatformIO/T41EEE-main/src':
   INFO - : 428 - 	No files found in this directory.
   INFO - :2349 - 
   INFO - :2350 - =======================================================================================================
   INFO - :2351 - [Step 3] Process all '.ino' and 'h' files extracting includes, global variables and 
   INFO - :2352 -          prototypes.. and insert Header Guards in all existing header files
   INFO - :2353 - =======================================================================================================
   INFO - :2361 - 
   INFO - :1227 - Processed arduinoGlue.h
   INFO - :1228 - Found and modified 0 include statements
   INFO - :1245 - 
   INFO - :1246 - Processing: extract_global_variables() from : arduinoGlue.h
   INFO - :1353 - 	[1] No global variables found
   INFO - :1364 - 
   INFO - :1365 - Processing: extract_constant_pointers() from : arduinoGlue.h
   INFO - :1377 - 	[2] Found 0 existing global variables for arduinoGlue in dict_global_variables
   INFO - :1546 - 
   INFO - :1547 - Processing: extract_prototypes() from file: [arduinoGlue.h]
   INFO - :2384 - 
   INFO - :2385 - And now the complete list of #includes:
   INFO - :2387 - And now the complete list of global variables:
   INFO - :2389 - And now the complete list of prototypes:
   INFO - : 333 - 	No functions found.
   INFO - :2392 - And now add all dict's to arduinoGlue.h:
   INFO - :1702 - 
   INFO - :1703 - Processing: update_arduino_glue()
   INFO - :2395 - 
   INFO - :2396 - =======================================================================================================
   INFO - :2397 - [Step 4] Create new header files for all '.ino' files
   INFO - :2398 - =======================================================================================================
   INFO - :2408 - 
   INFO - :2409 - =======================================================================================================
   INFO - :2410 - [Step 5] add all local includes to the 'project_name.ino' file  (insert '#include "x.h"' to x.ino)
   INFO - :2411 - =======================================================================================================
   INFO - :1083 - 
   INFO - :1084 - Processing: add_local_includes_to_project_header(): T41EEE-main
  ERROR - :1146 - 	An error occurred at line 1089: [Errno 2] No such file or directory: '/Users/freddie/Desktop/T41EEE-main/PlatformIO/T41EEE-main/include/T41EEE-main.h'
freddie@Eds-MacBook-Pro T41EEE-main % 

Any ideas on how to correct this issue?

**Comment by mrWheel** [comment]
@sbfreddie ,

I have no idea what is going on here.

there is no `PlatformIO` folder with the converted files.
But what I see is that the code is very specific and tuned to a specific processor.
